//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessInitParameters) DeepCopyInto(out *AccessInitParameters) {
	*out = *in
	if in.AudTag != nil {
		in, out := &in.AudTag, &out.AudTag
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.TeamName != nil {
		in, out := &in.TeamName, &out.TeamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessInitParameters.
func (in *AccessInitParameters) DeepCopy() *AccessInitParameters {
	if in == nil {
		return nil
	}
	out := new(AccessInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessObservation) DeepCopyInto(out *AccessObservation) {
	*out = *in
	if in.AudTag != nil {
		in, out := &in.AudTag, &out.AudTag
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.TeamName != nil {
		in, out := &in.TeamName, &out.TeamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessObservation.
func (in *AccessObservation) DeepCopy() *AccessObservation {
	if in == nil {
		return nil
	}
	out := new(AccessObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessParameters) DeepCopyInto(out *AccessParameters) {
	*out = *in
	if in.AudTag != nil {
		in, out := &in.AudTag, &out.AudTag
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.TeamName != nil {
		in, out := &in.TeamName, &out.TeamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessParameters.
func (in *AccessParameters) DeepCopy() *AccessParameters {
	if in == nil {
		return nil
	}
	out := new(AccessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigInitParameters) DeepCopyInto(out *ConfigInitParameters) {
	*out = *in
	if in.IngressRule != nil {
		in, out := &in.IngressRule, &out.IngressRule
		*out = make([]IngressRuleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OriginRequest != nil {
		in, out := &in.OriginRequest, &out.OriginRequest
		*out = make([]ConfigOriginRequestInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WarpRouting != nil {
		in, out := &in.WarpRouting, &out.WarpRouting
		*out = make([]WarpRoutingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigInitParameters.
func (in *ConfigInitParameters) DeepCopy() *ConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObservation) DeepCopyInto(out *ConfigObservation) {
	*out = *in
	if in.IngressRule != nil {
		in, out := &in.IngressRule, &out.IngressRule
		*out = make([]IngressRuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OriginRequest != nil {
		in, out := &in.OriginRequest, &out.OriginRequest
		*out = make([]ConfigOriginRequestObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WarpRouting != nil {
		in, out := &in.WarpRouting, &out.WarpRouting
		*out = make([]WarpRoutingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObservation.
func (in *ConfigObservation) DeepCopy() *ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOriginRequestInitParameters) DeepCopyInto(out *ConfigOriginRequestInitParameters) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]OriginRequestAccessInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BastionMode != nil {
		in, out := &in.BastionMode, &out.BastionMode
		*out = new(bool)
		**out = **in
	}
	if in.CAPool != nil {
		in, out := &in.CAPool, &out.CAPool
		*out = new(string)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(string)
		**out = **in
	}
	if in.DisableChunkedEncoding != nil {
		in, out := &in.DisableChunkedEncoding, &out.DisableChunkedEncoding
		*out = new(bool)
		**out = **in
	}
	if in.HTTPHostHeader != nil {
		in, out := &in.HTTPHostHeader, &out.HTTPHostHeader
		*out = new(string)
		**out = **in
	}
	if in.Http2Origin != nil {
		in, out := &in.Http2Origin, &out.Http2Origin
		*out = new(bool)
		**out = **in
	}
	if in.IPRules != nil {
		in, out := &in.IPRules, &out.IPRules
		*out = make([]OriginRequestIPRulesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeepAliveConnections != nil {
		in, out := &in.KeepAliveConnections, &out.KeepAliveConnections
		*out = new(float64)
		**out = **in
	}
	if in.KeepAliveTimeout != nil {
		in, out := &in.KeepAliveTimeout, &out.KeepAliveTimeout
		*out = new(string)
		**out = **in
	}
	if in.NoHappyEyeballs != nil {
		in, out := &in.NoHappyEyeballs, &out.NoHappyEyeballs
		*out = new(bool)
		**out = **in
	}
	if in.NoTLSVerify != nil {
		in, out := &in.NoTLSVerify, &out.NoTLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.OriginServerName != nil {
		in, out := &in.OriginServerName, &out.OriginServerName
		*out = new(string)
		**out = **in
	}
	if in.ProxyAddress != nil {
		in, out := &in.ProxyAddress, &out.ProxyAddress
		*out = new(string)
		**out = **in
	}
	if in.ProxyPort != nil {
		in, out := &in.ProxyPort, &out.ProxyPort
		*out = new(float64)
		**out = **in
	}
	if in.ProxyType != nil {
		in, out := &in.ProxyType, &out.ProxyType
		*out = new(string)
		**out = **in
	}
	if in.TCPKeepAlive != nil {
		in, out := &in.TCPKeepAlive, &out.TCPKeepAlive
		*out = new(string)
		**out = **in
	}
	if in.TLSTimeout != nil {
		in, out := &in.TLSTimeout, &out.TLSTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOriginRequestInitParameters.
func (in *ConfigOriginRequestInitParameters) DeepCopy() *ConfigOriginRequestInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigOriginRequestInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOriginRequestObservation) DeepCopyInto(out *ConfigOriginRequestObservation) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]OriginRequestAccessObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BastionMode != nil {
		in, out := &in.BastionMode, &out.BastionMode
		*out = new(bool)
		**out = **in
	}
	if in.CAPool != nil {
		in, out := &in.CAPool, &out.CAPool
		*out = new(string)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(string)
		**out = **in
	}
	if in.DisableChunkedEncoding != nil {
		in, out := &in.DisableChunkedEncoding, &out.DisableChunkedEncoding
		*out = new(bool)
		**out = **in
	}
	if in.HTTPHostHeader != nil {
		in, out := &in.HTTPHostHeader, &out.HTTPHostHeader
		*out = new(string)
		**out = **in
	}
	if in.Http2Origin != nil {
		in, out := &in.Http2Origin, &out.Http2Origin
		*out = new(bool)
		**out = **in
	}
	if in.IPRules != nil {
		in, out := &in.IPRules, &out.IPRules
		*out = make([]OriginRequestIPRulesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeepAliveConnections != nil {
		in, out := &in.KeepAliveConnections, &out.KeepAliveConnections
		*out = new(float64)
		**out = **in
	}
	if in.KeepAliveTimeout != nil {
		in, out := &in.KeepAliveTimeout, &out.KeepAliveTimeout
		*out = new(string)
		**out = **in
	}
	if in.NoHappyEyeballs != nil {
		in, out := &in.NoHappyEyeballs, &out.NoHappyEyeballs
		*out = new(bool)
		**out = **in
	}
	if in.NoTLSVerify != nil {
		in, out := &in.NoTLSVerify, &out.NoTLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.OriginServerName != nil {
		in, out := &in.OriginServerName, &out.OriginServerName
		*out = new(string)
		**out = **in
	}
	if in.ProxyAddress != nil {
		in, out := &in.ProxyAddress, &out.ProxyAddress
		*out = new(string)
		**out = **in
	}
	if in.ProxyPort != nil {
		in, out := &in.ProxyPort, &out.ProxyPort
		*out = new(float64)
		**out = **in
	}
	if in.ProxyType != nil {
		in, out := &in.ProxyType, &out.ProxyType
		*out = new(string)
		**out = **in
	}
	if in.TCPKeepAlive != nil {
		in, out := &in.TCPKeepAlive, &out.TCPKeepAlive
		*out = new(string)
		**out = **in
	}
	if in.TLSTimeout != nil {
		in, out := &in.TLSTimeout, &out.TLSTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOriginRequestObservation.
func (in *ConfigOriginRequestObservation) DeepCopy() *ConfigOriginRequestObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigOriginRequestObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOriginRequestParameters) DeepCopyInto(out *ConfigOriginRequestParameters) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]OriginRequestAccessParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BastionMode != nil {
		in, out := &in.BastionMode, &out.BastionMode
		*out = new(bool)
		**out = **in
	}
	if in.CAPool != nil {
		in, out := &in.CAPool, &out.CAPool
		*out = new(string)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(string)
		**out = **in
	}
	if in.DisableChunkedEncoding != nil {
		in, out := &in.DisableChunkedEncoding, &out.DisableChunkedEncoding
		*out = new(bool)
		**out = **in
	}
	if in.HTTPHostHeader != nil {
		in, out := &in.HTTPHostHeader, &out.HTTPHostHeader
		*out = new(string)
		**out = **in
	}
	if in.Http2Origin != nil {
		in, out := &in.Http2Origin, &out.Http2Origin
		*out = new(bool)
		**out = **in
	}
	if in.IPRules != nil {
		in, out := &in.IPRules, &out.IPRules
		*out = make([]OriginRequestIPRulesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeepAliveConnections != nil {
		in, out := &in.KeepAliveConnections, &out.KeepAliveConnections
		*out = new(float64)
		**out = **in
	}
	if in.KeepAliveTimeout != nil {
		in, out := &in.KeepAliveTimeout, &out.KeepAliveTimeout
		*out = new(string)
		**out = **in
	}
	if in.NoHappyEyeballs != nil {
		in, out := &in.NoHappyEyeballs, &out.NoHappyEyeballs
		*out = new(bool)
		**out = **in
	}
	if in.NoTLSVerify != nil {
		in, out := &in.NoTLSVerify, &out.NoTLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.OriginServerName != nil {
		in, out := &in.OriginServerName, &out.OriginServerName
		*out = new(string)
		**out = **in
	}
	if in.ProxyAddress != nil {
		in, out := &in.ProxyAddress, &out.ProxyAddress
		*out = new(string)
		**out = **in
	}
	if in.ProxyPort != nil {
		in, out := &in.ProxyPort, &out.ProxyPort
		*out = new(float64)
		**out = **in
	}
	if in.ProxyType != nil {
		in, out := &in.ProxyType, &out.ProxyType
		*out = new(string)
		**out = **in
	}
	if in.TCPKeepAlive != nil {
		in, out := &in.TCPKeepAlive, &out.TCPKeepAlive
		*out = new(string)
		**out = **in
	}
	if in.TLSTimeout != nil {
		in, out := &in.TLSTimeout, &out.TLSTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOriginRequestParameters.
func (in *ConfigOriginRequestParameters) DeepCopy() *ConfigOriginRequestParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigOriginRequestParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigParameters) DeepCopyInto(out *ConfigParameters) {
	*out = *in
	if in.IngressRule != nil {
		in, out := &in.IngressRule, &out.IngressRule
		*out = make([]IngressRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OriginRequest != nil {
		in, out := &in.OriginRequest, &out.OriginRequest
		*out = make([]ConfigOriginRequestParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WarpRouting != nil {
		in, out := &in.WarpRouting, &out.WarpRouting
		*out = make([]WarpRoutingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigParameters.
func (in *ConfigParameters) DeepCopy() *ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPRulesInitParameters) DeepCopyInto(out *IPRulesInitParameters) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(bool)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPRulesInitParameters.
func (in *IPRulesInitParameters) DeepCopy() *IPRulesInitParameters {
	if in == nil {
		return nil
	}
	out := new(IPRulesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPRulesObservation) DeepCopyInto(out *IPRulesObservation) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(bool)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPRulesObservation.
func (in *IPRulesObservation) DeepCopy() *IPRulesObservation {
	if in == nil {
		return nil
	}
	out := new(IPRulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPRulesParameters) DeepCopyInto(out *IPRulesParameters) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(bool)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPRulesParameters.
func (in *IPRulesParameters) DeepCopy() *IPRulesParameters {
	if in == nil {
		return nil
	}
	out := new(IPRulesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRuleInitParameters) DeepCopyInto(out *IngressRuleInitParameters) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.OriginRequest != nil {
		in, out := &in.OriginRequest, &out.OriginRequest
		*out = make([]OriginRequestInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRuleInitParameters.
func (in *IngressRuleInitParameters) DeepCopy() *IngressRuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(IngressRuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRuleObservation) DeepCopyInto(out *IngressRuleObservation) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.OriginRequest != nil {
		in, out := &in.OriginRequest, &out.OriginRequest
		*out = make([]OriginRequestObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRuleObservation.
func (in *IngressRuleObservation) DeepCopy() *IngressRuleObservation {
	if in == nil {
		return nil
	}
	out := new(IngressRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRuleParameters) DeepCopyInto(out *IngressRuleParameters) {
	*out = *in
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.OriginRequest != nil {
		in, out := &in.OriginRequest, &out.OriginRequest
		*out = make([]OriginRequestParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRuleParameters.
func (in *IngressRuleParameters) DeepCopy() *IngressRuleParameters {
	if in == nil {
		return nil
	}
	out := new(IngressRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestAccessInitParameters) DeepCopyInto(out *OriginRequestAccessInitParameters) {
	*out = *in
	if in.AudTag != nil {
		in, out := &in.AudTag, &out.AudTag
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.TeamName != nil {
		in, out := &in.TeamName, &out.TeamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestAccessInitParameters.
func (in *OriginRequestAccessInitParameters) DeepCopy() *OriginRequestAccessInitParameters {
	if in == nil {
		return nil
	}
	out := new(OriginRequestAccessInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestAccessObservation) DeepCopyInto(out *OriginRequestAccessObservation) {
	*out = *in
	if in.AudTag != nil {
		in, out := &in.AudTag, &out.AudTag
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.TeamName != nil {
		in, out := &in.TeamName, &out.TeamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestAccessObservation.
func (in *OriginRequestAccessObservation) DeepCopy() *OriginRequestAccessObservation {
	if in == nil {
		return nil
	}
	out := new(OriginRequestAccessObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestAccessParameters) DeepCopyInto(out *OriginRequestAccessParameters) {
	*out = *in
	if in.AudTag != nil {
		in, out := &in.AudTag, &out.AudTag
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.TeamName != nil {
		in, out := &in.TeamName, &out.TeamName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestAccessParameters.
func (in *OriginRequestAccessParameters) DeepCopy() *OriginRequestAccessParameters {
	if in == nil {
		return nil
	}
	out := new(OriginRequestAccessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestIPRulesInitParameters) DeepCopyInto(out *OriginRequestIPRulesInitParameters) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(bool)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestIPRulesInitParameters.
func (in *OriginRequestIPRulesInitParameters) DeepCopy() *OriginRequestIPRulesInitParameters {
	if in == nil {
		return nil
	}
	out := new(OriginRequestIPRulesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestIPRulesObservation) DeepCopyInto(out *OriginRequestIPRulesObservation) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(bool)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestIPRulesObservation.
func (in *OriginRequestIPRulesObservation) DeepCopy() *OriginRequestIPRulesObservation {
	if in == nil {
		return nil
	}
	out := new(OriginRequestIPRulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestIPRulesParameters) DeepCopyInto(out *OriginRequestIPRulesParameters) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(bool)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestIPRulesParameters.
func (in *OriginRequestIPRulesParameters) DeepCopy() *OriginRequestIPRulesParameters {
	if in == nil {
		return nil
	}
	out := new(OriginRequestIPRulesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestInitParameters) DeepCopyInto(out *OriginRequestInitParameters) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]AccessInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BastionMode != nil {
		in, out := &in.BastionMode, &out.BastionMode
		*out = new(bool)
		**out = **in
	}
	if in.CAPool != nil {
		in, out := &in.CAPool, &out.CAPool
		*out = new(string)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(string)
		**out = **in
	}
	if in.DisableChunkedEncoding != nil {
		in, out := &in.DisableChunkedEncoding, &out.DisableChunkedEncoding
		*out = new(bool)
		**out = **in
	}
	if in.HTTPHostHeader != nil {
		in, out := &in.HTTPHostHeader, &out.HTTPHostHeader
		*out = new(string)
		**out = **in
	}
	if in.Http2Origin != nil {
		in, out := &in.Http2Origin, &out.Http2Origin
		*out = new(bool)
		**out = **in
	}
	if in.IPRules != nil {
		in, out := &in.IPRules, &out.IPRules
		*out = make([]IPRulesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeepAliveConnections != nil {
		in, out := &in.KeepAliveConnections, &out.KeepAliveConnections
		*out = new(float64)
		**out = **in
	}
	if in.KeepAliveTimeout != nil {
		in, out := &in.KeepAliveTimeout, &out.KeepAliveTimeout
		*out = new(string)
		**out = **in
	}
	if in.NoHappyEyeballs != nil {
		in, out := &in.NoHappyEyeballs, &out.NoHappyEyeballs
		*out = new(bool)
		**out = **in
	}
	if in.NoTLSVerify != nil {
		in, out := &in.NoTLSVerify, &out.NoTLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.OriginServerName != nil {
		in, out := &in.OriginServerName, &out.OriginServerName
		*out = new(string)
		**out = **in
	}
	if in.ProxyAddress != nil {
		in, out := &in.ProxyAddress, &out.ProxyAddress
		*out = new(string)
		**out = **in
	}
	if in.ProxyPort != nil {
		in, out := &in.ProxyPort, &out.ProxyPort
		*out = new(float64)
		**out = **in
	}
	if in.ProxyType != nil {
		in, out := &in.ProxyType, &out.ProxyType
		*out = new(string)
		**out = **in
	}
	if in.TCPKeepAlive != nil {
		in, out := &in.TCPKeepAlive, &out.TCPKeepAlive
		*out = new(string)
		**out = **in
	}
	if in.TLSTimeout != nil {
		in, out := &in.TLSTimeout, &out.TLSTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestInitParameters.
func (in *OriginRequestInitParameters) DeepCopy() *OriginRequestInitParameters {
	if in == nil {
		return nil
	}
	out := new(OriginRequestInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestObservation) DeepCopyInto(out *OriginRequestObservation) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]AccessObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BastionMode != nil {
		in, out := &in.BastionMode, &out.BastionMode
		*out = new(bool)
		**out = **in
	}
	if in.CAPool != nil {
		in, out := &in.CAPool, &out.CAPool
		*out = new(string)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(string)
		**out = **in
	}
	if in.DisableChunkedEncoding != nil {
		in, out := &in.DisableChunkedEncoding, &out.DisableChunkedEncoding
		*out = new(bool)
		**out = **in
	}
	if in.HTTPHostHeader != nil {
		in, out := &in.HTTPHostHeader, &out.HTTPHostHeader
		*out = new(string)
		**out = **in
	}
	if in.Http2Origin != nil {
		in, out := &in.Http2Origin, &out.Http2Origin
		*out = new(bool)
		**out = **in
	}
	if in.IPRules != nil {
		in, out := &in.IPRules, &out.IPRules
		*out = make([]IPRulesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeepAliveConnections != nil {
		in, out := &in.KeepAliveConnections, &out.KeepAliveConnections
		*out = new(float64)
		**out = **in
	}
	if in.KeepAliveTimeout != nil {
		in, out := &in.KeepAliveTimeout, &out.KeepAliveTimeout
		*out = new(string)
		**out = **in
	}
	if in.NoHappyEyeballs != nil {
		in, out := &in.NoHappyEyeballs, &out.NoHappyEyeballs
		*out = new(bool)
		**out = **in
	}
	if in.NoTLSVerify != nil {
		in, out := &in.NoTLSVerify, &out.NoTLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.OriginServerName != nil {
		in, out := &in.OriginServerName, &out.OriginServerName
		*out = new(string)
		**out = **in
	}
	if in.ProxyAddress != nil {
		in, out := &in.ProxyAddress, &out.ProxyAddress
		*out = new(string)
		**out = **in
	}
	if in.ProxyPort != nil {
		in, out := &in.ProxyPort, &out.ProxyPort
		*out = new(float64)
		**out = **in
	}
	if in.ProxyType != nil {
		in, out := &in.ProxyType, &out.ProxyType
		*out = new(string)
		**out = **in
	}
	if in.TCPKeepAlive != nil {
		in, out := &in.TCPKeepAlive, &out.TCPKeepAlive
		*out = new(string)
		**out = **in
	}
	if in.TLSTimeout != nil {
		in, out := &in.TLSTimeout, &out.TLSTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestObservation.
func (in *OriginRequestObservation) DeepCopy() *OriginRequestObservation {
	if in == nil {
		return nil
	}
	out := new(OriginRequestObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginRequestParameters) DeepCopyInto(out *OriginRequestParameters) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]AccessParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BastionMode != nil {
		in, out := &in.BastionMode, &out.BastionMode
		*out = new(bool)
		**out = **in
	}
	if in.CAPool != nil {
		in, out := &in.CAPool, &out.CAPool
		*out = new(string)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(string)
		**out = **in
	}
	if in.DisableChunkedEncoding != nil {
		in, out := &in.DisableChunkedEncoding, &out.DisableChunkedEncoding
		*out = new(bool)
		**out = **in
	}
	if in.HTTPHostHeader != nil {
		in, out := &in.HTTPHostHeader, &out.HTTPHostHeader
		*out = new(string)
		**out = **in
	}
	if in.Http2Origin != nil {
		in, out := &in.Http2Origin, &out.Http2Origin
		*out = new(bool)
		**out = **in
	}
	if in.IPRules != nil {
		in, out := &in.IPRules, &out.IPRules
		*out = make([]IPRulesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeepAliveConnections != nil {
		in, out := &in.KeepAliveConnections, &out.KeepAliveConnections
		*out = new(float64)
		**out = **in
	}
	if in.KeepAliveTimeout != nil {
		in, out := &in.KeepAliveTimeout, &out.KeepAliveTimeout
		*out = new(string)
		**out = **in
	}
	if in.NoHappyEyeballs != nil {
		in, out := &in.NoHappyEyeballs, &out.NoHappyEyeballs
		*out = new(bool)
		**out = **in
	}
	if in.NoTLSVerify != nil {
		in, out := &in.NoTLSVerify, &out.NoTLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.OriginServerName != nil {
		in, out := &in.OriginServerName, &out.OriginServerName
		*out = new(string)
		**out = **in
	}
	if in.ProxyAddress != nil {
		in, out := &in.ProxyAddress, &out.ProxyAddress
		*out = new(string)
		**out = **in
	}
	if in.ProxyPort != nil {
		in, out := &in.ProxyPort, &out.ProxyPort
		*out = new(float64)
		**out = **in
	}
	if in.ProxyType != nil {
		in, out := &in.ProxyType, &out.ProxyType
		*out = new(string)
		**out = **in
	}
	if in.TCPKeepAlive != nil {
		in, out := &in.TCPKeepAlive, &out.TCPKeepAlive
		*out = new(string)
		**out = **in
	}
	if in.TLSTimeout != nil {
		in, out := &in.TLSTimeout, &out.TLSTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginRequestParameters.
func (in *OriginRequestParameters) DeepCopy() *OriginRequestParameters {
	if in == nil {
		return nil
	}
	out := new(OriginRequestParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route) DeepCopyInto(out *Route) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route.
func (in *Route) DeepCopy() *Route {
	if in == nil {
		return nil
	}
	out := new(Route)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Route) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteInitParameters) DeepCopyInto(out *RouteInitParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.TunnelID != nil {
		in, out := &in.TunnelID, &out.TunnelID
		*out = new(string)
		**out = **in
	}
	if in.VirtualNetworkID != nil {
		in, out := &in.VirtualNetworkID, &out.VirtualNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteInitParameters.
func (in *RouteInitParameters) DeepCopy() *RouteInitParameters {
	if in == nil {
		return nil
	}
	out := new(RouteInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteList) DeepCopyInto(out *RouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Route, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteList.
func (in *RouteList) DeepCopy() *RouteList {
	if in == nil {
		return nil
	}
	out := new(RouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteObservation) DeepCopyInto(out *RouteObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.TunnelID != nil {
		in, out := &in.TunnelID, &out.TunnelID
		*out = new(string)
		**out = **in
	}
	if in.VirtualNetworkID != nil {
		in, out := &in.VirtualNetworkID, &out.VirtualNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteObservation.
func (in *RouteObservation) DeepCopy() *RouteObservation {
	if in == nil {
		return nil
	}
	out := new(RouteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteParameters) DeepCopyInto(out *RouteParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.TunnelID != nil {
		in, out := &in.TunnelID, &out.TunnelID
		*out = new(string)
		**out = **in
	}
	if in.VirtualNetworkID != nil {
		in, out := &in.VirtualNetworkID, &out.VirtualNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteParameters.
func (in *RouteParameters) DeepCopy() *RouteParameters {
	if in == nil {
		return nil
	}
	out := new(RouteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteSpec) DeepCopyInto(out *RouteSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteSpec.
func (in *RouteSpec) DeepCopy() *RouteSpec {
	if in == nil {
		return nil
	}
	out := new(RouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteStatus) DeepCopyInto(out *RouteStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteStatus.
func (in *RouteStatus) DeepCopy() *RouteStatus {
	if in == nil {
		return nil
	}
	out := new(RouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tunnel) DeepCopyInto(out *Tunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tunnel.
func (in *Tunnel) DeepCopy() *Tunnel {
	if in == nil {
		return nil
	}
	out := new(Tunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelConfig) DeepCopyInto(out *TunnelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelConfig.
func (in *TunnelConfig) DeepCopy() *TunnelConfig {
	if in == nil {
		return nil
	}
	out := new(TunnelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TunnelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelConfigInitParameters) DeepCopyInto(out *TunnelConfigInitParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TunnelID != nil {
		in, out := &in.TunnelID, &out.TunnelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelConfigInitParameters.
func (in *TunnelConfigInitParameters) DeepCopy() *TunnelConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(TunnelConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelConfigList) DeepCopyInto(out *TunnelConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TunnelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelConfigList.
func (in *TunnelConfigList) DeepCopy() *TunnelConfigList {
	if in == nil {
		return nil
	}
	out := new(TunnelConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TunnelConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelConfigObservation) DeepCopyInto(out *TunnelConfigObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.TunnelID != nil {
		in, out := &in.TunnelID, &out.TunnelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelConfigObservation.
func (in *TunnelConfigObservation) DeepCopy() *TunnelConfigObservation {
	if in == nil {
		return nil
	}
	out := new(TunnelConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelConfigParameters) DeepCopyInto(out *TunnelConfigParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TunnelID != nil {
		in, out := &in.TunnelID, &out.TunnelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelConfigParameters.
func (in *TunnelConfigParameters) DeepCopy() *TunnelConfigParameters {
	if in == nil {
		return nil
	}
	out := new(TunnelConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelConfigSpec) DeepCopyInto(out *TunnelConfigSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelConfigSpec.
func (in *TunnelConfigSpec) DeepCopy() *TunnelConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TunnelConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelConfigStatus) DeepCopyInto(out *TunnelConfigStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelConfigStatus.
func (in *TunnelConfigStatus) DeepCopy() *TunnelConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TunnelConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelInitParameters) DeepCopyInto(out *TunnelInitParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.ConfigSrc != nil {
		in, out := &in.ConfigSrc, &out.ConfigSrc
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.SecretSecretRef.DeepCopyInto(&out.SecretSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelInitParameters.
func (in *TunnelInitParameters) DeepCopy() *TunnelInitParameters {
	if in == nil {
		return nil
	}
	out := new(TunnelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelList) DeepCopyInto(out *TunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelList.
func (in *TunnelList) DeepCopy() *TunnelList {
	if in == nil {
		return nil
	}
	out := new(TunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelObservation) DeepCopyInto(out *TunnelObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Cname != nil {
		in, out := &in.Cname, &out.Cname
		*out = new(string)
		**out = **in
	}
	if in.ConfigSrc != nil {
		in, out := &in.ConfigSrc, &out.ConfigSrc
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelObservation.
func (in *TunnelObservation) DeepCopy() *TunnelObservation {
	if in == nil {
		return nil
	}
	out := new(TunnelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelParameters) DeepCopyInto(out *TunnelParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.ConfigSrc != nil {
		in, out := &in.ConfigSrc, &out.ConfigSrc
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.SecretSecretRef.DeepCopyInto(&out.SecretSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelParameters.
func (in *TunnelParameters) DeepCopy() *TunnelParameters {
	if in == nil {
		return nil
	}
	out := new(TunnelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelSpec) DeepCopyInto(out *TunnelSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelSpec.
func (in *TunnelSpec) DeepCopy() *TunnelSpec {
	if in == nil {
		return nil
	}
	out := new(TunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelStatus) DeepCopyInto(out *TunnelStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelStatus.
func (in *TunnelStatus) DeepCopy() *TunnelStatus {
	if in == nil {
		return nil
	}
	out := new(TunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpRoutingInitParameters) DeepCopyInto(out *WarpRoutingInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpRoutingInitParameters.
func (in *WarpRoutingInitParameters) DeepCopy() *WarpRoutingInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarpRoutingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpRoutingObservation) DeepCopyInto(out *WarpRoutingObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpRoutingObservation.
func (in *WarpRoutingObservation) DeepCopy() *WarpRoutingObservation {
	if in == nil {
		return nil
	}
	out := new(WarpRoutingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpRoutingParameters) DeepCopyInto(out *WarpRoutingParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpRoutingParameters.
func (in *WarpRoutingParameters) DeepCopy() *WarpRoutingParameters {
	if in == nil {
		return nil
	}
	out := new(WarpRoutingParameters)
	in.DeepCopyInto(out)
	return out
}
