apiVersion: tunnel.cloudflare./v1alpha1
kind: TunnelConfig
metadata:
  annotations:
    meta.upbound.io/example-id: tunnel/v1alpha1/tunnelconfig
  labels:
    testing.upbound.io/example-name: example_config
  name: example-config
spec:
  forProvider:
    accountId: f037e56e89293a057740de681ac9abbe
    config:
    - ingressRule:
      - hostname: foo
        originRequest:
        - access:
          - audTag:
            - AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            required: true
            teamName: terraform
          connectTimeout: 2m0s
        path: /bar
        service: http://10.0.0.2:8080
      - service: https://10.0.0.3:8081
      originRequest:
      - bastionMode: false
        caPool: /path/to/unsigned/ca/pool
        connectTimeout: 1m0s
        disableChunkedEncoding: false
        httpHostHeader: baz
        ipRules:
        - allow: false
          ports:
          - 80
          - 443
          prefix: /web
        keepAliveConnections: 1024
        keepAliveTimeout: 1m0s
        noHappyEyeballs: false
        noTlsVerify: false
        originServerName: foobar
        proxyAddress: 10.0.0.1
        proxyPort: "8123"
        proxyType: socks
        tcpKeepAlive: 1m0s
        tlsTimeout: 1m0s
      warpRouting:
      - enabled: true
    tunnelId: ${cloudflare_zero_trust_tunnel_cloudflared.example_tunnel.id}
