// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AuthContextInitParameters struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type AuthContextObservation struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type AuthContextParameters struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	// +kubebuilder:validation:Optional
	AcID *string `json:"acId" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type AzureInitParameters struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type AzureObservation struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type AzureParameters struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	// +kubebuilder:validation:Optional
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type ExcludeInitParameters struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	AuthContext []AuthContextInitParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	Azure []AzureInitParameters `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	ExternalEvaluation []ExternalEvaluationInitParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	Github []GithubInitParameters `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	Gsuite []GsuiteInitParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	Okta []OktaInitParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	SAML []SAMLInitParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type ExcludeObservation struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	AuthContext []AuthContextObservation `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	Azure []AzureObservation `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	ExternalEvaluation []ExternalEvaluationObservation `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	Github []GithubObservation `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	Gsuite []GsuiteObservation `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	Okta []OktaObservation `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	SAML []SAMLObservation `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type ExcludeParameters struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	// +kubebuilder:validation:Optional
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AuthContext []AuthContextParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	// +kubebuilder:validation:Optional
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	// +kubebuilder:validation:Optional
	Azure []AzureParameters `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	// +kubebuilder:validation:Optional
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// +kubebuilder:validation:Optional
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	// +kubebuilder:validation:Optional
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	// +kubebuilder:validation:Optional
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	// +kubebuilder:validation:Optional
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	// +kubebuilder:validation:Optional
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	// +kubebuilder:validation:Optional
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	// +kubebuilder:validation:Optional
	ExternalEvaluation []ExternalEvaluationParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	// +kubebuilder:validation:Optional
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	// +kubebuilder:validation:Optional
	Github []GithubParameters `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	// +kubebuilder:validation:Optional
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	Gsuite []GsuiteParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	// +kubebuilder:validation:Optional
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	// +kubebuilder:validation:Optional
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	// +kubebuilder:validation:Optional
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	// +kubebuilder:validation:Optional
	Okta []OktaParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	// +kubebuilder:validation:Optional
	SAML []SAMLParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	// +kubebuilder:validation:Optional
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type ExternalEvaluationInitParameters struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type ExternalEvaluationObservation struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type ExternalEvaluationParameters struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	// +kubebuilder:validation:Optional
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	// +kubebuilder:validation:Optional
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type GithubInitParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type GithubObservation struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type GithubParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	// +kubebuilder:validation:Optional
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type GroupInitParameters struct {

	// (String) The account identifier to target for the resource. Conflicts with zone_id. Modifying this attribute will force creation of a new resource.
	// The account identifier to target for the resource. Conflicts with `zone_id`. **Modifying this attribute will force creation of a new resource.**
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Block List) (see below for nested schema)
	Exclude []ExcludeInitParameters `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	Include []IncludeInitParameters `json:"include,omitempty" tf:"include,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List) (see below for nested schema)
	Require []RequireInitParameters `json:"require,omitempty" tf:"require,omitempty"`

	// (String) The zone identifier to target for the resource. Conflicts with account_id.
	// The zone identifier to target for the resource. Conflicts with `account_id`.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type GroupObservation struct {

	// (String) The account identifier to target for the resource. Conflicts with zone_id. Modifying this attribute will force creation of a new resource.
	// The account identifier to target for the resource. Conflicts with `zone_id`. **Modifying this attribute will force creation of a new resource.**
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Block List) (see below for nested schema)
	Exclude []ExcludeObservation `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	Include []IncludeObservation `json:"include,omitempty" tf:"include,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List) (see below for nested schema)
	Require []RequireObservation `json:"require,omitempty" tf:"require,omitempty"`

	// (String) The zone identifier to target for the resource. Conflicts with account_id.
	// The zone identifier to target for the resource. Conflicts with `account_id`.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type GroupParameters struct {

	// (String) The account identifier to target for the resource. Conflicts with zone_id. Modifying this attribute will force creation of a new resource.
	// The account identifier to target for the resource. Conflicts with `zone_id`. **Modifying this attribute will force creation of a new resource.**
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Block List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Exclude []ExcludeParameters `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Block List, Min: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Include []IncludeParameters `json:"include,omitempty" tf:"include,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Require []RequireParameters `json:"require,omitempty" tf:"require,omitempty"`

	// (String) The zone identifier to target for the resource. Conflicts with account_id.
	// The zone identifier to target for the resource. Conflicts with `account_id`.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type GsuiteInitParameters struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type GsuiteObservation struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type GsuiteParameters struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	// +kubebuilder:validation:Optional
	Email []*string `json:"email" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type IncludeAuthContextInitParameters struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeAuthContextObservation struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeAuthContextParameters struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	// +kubebuilder:validation:Optional
	AcID *string `json:"acId" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type IncludeAzureInitParameters struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeAzureObservation struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeAzureParameters struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	// +kubebuilder:validation:Optional
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeExternalEvaluationInitParameters struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type IncludeExternalEvaluationObservation struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type IncludeExternalEvaluationParameters struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	// +kubebuilder:validation:Optional
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	// +kubebuilder:validation:Optional
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type IncludeGithubInitParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type IncludeGithubObservation struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type IncludeGithubParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	// +kubebuilder:validation:Optional
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type IncludeGsuiteInitParameters struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeGsuiteObservation struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeGsuiteParameters struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	// +kubebuilder:validation:Optional
	Email []*string `json:"email" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type IncludeInitParameters struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	AuthContext []IncludeAuthContextInitParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	Azure []IncludeAzureInitParameters `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	ExternalEvaluation []IncludeExternalEvaluationInitParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	Github []IncludeGithubInitParameters `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	Gsuite []IncludeGsuiteInitParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	Okta []IncludeOktaInitParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	SAML []IncludeSAMLInitParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type IncludeObservation struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	AuthContext []IncludeAuthContextObservation `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	Azure []IncludeAzureObservation `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	ExternalEvaluation []IncludeExternalEvaluationObservation `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	Github []IncludeGithubObservation `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	Gsuite []IncludeGsuiteObservation `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	Okta []IncludeOktaObservation `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	SAML []IncludeSAMLObservation `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type IncludeOktaInitParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type IncludeOktaObservation struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type IncludeOktaParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	// +kubebuilder:validation:Optional
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type IncludeParameters struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	// +kubebuilder:validation:Optional
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AuthContext []IncludeAuthContextParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	// +kubebuilder:validation:Optional
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	// +kubebuilder:validation:Optional
	Azure []IncludeAzureParameters `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	// +kubebuilder:validation:Optional
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// +kubebuilder:validation:Optional
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	// +kubebuilder:validation:Optional
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	// +kubebuilder:validation:Optional
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	// +kubebuilder:validation:Optional
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	// +kubebuilder:validation:Optional
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	// +kubebuilder:validation:Optional
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	// +kubebuilder:validation:Optional
	ExternalEvaluation []IncludeExternalEvaluationParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	// +kubebuilder:validation:Optional
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	// +kubebuilder:validation:Optional
	Github []IncludeGithubParameters `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	// +kubebuilder:validation:Optional
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	Gsuite []IncludeGsuiteParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	// +kubebuilder:validation:Optional
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	// +kubebuilder:validation:Optional
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	// +kubebuilder:validation:Optional
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	// +kubebuilder:validation:Optional
	Okta []IncludeOktaParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	// +kubebuilder:validation:Optional
	SAML []IncludeSAMLParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	// +kubebuilder:validation:Optional
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type IncludeSAMLInitParameters struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeSAMLObservation struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type IncludeSAMLParameters struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	// +kubebuilder:validation:Optional
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	// +kubebuilder:validation:Optional
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type OktaInitParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type OktaObservation struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type OktaParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	// +kubebuilder:validation:Optional
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type RequireAuthContextInitParameters struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireAuthContextObservation struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireAuthContextParameters struct {

	// (String) The ACID of the Authentication Context.
	// The ACID of the Authentication Context.
	// +kubebuilder:validation:Optional
	AcID *string `json:"acId" tf:"ac_id,omitempty"`

	// (String) The ID of this resource.
	// The ID of the Authentication Context.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type RequireAzureInitParameters struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireAzureObservation struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireAzureParameters struct {

	// (String) The ID of this resource.
	// The ID of the Azure group or user.
	// +kubebuilder:validation:Optional
	ID []*string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of the Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireExternalEvaluationInitParameters struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type RequireExternalEvaluationObservation struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type RequireExternalEvaluationParameters struct {

	// (String) The API endpoint containing your business logic.
	// The API endpoint containing your business logic.
	// +kubebuilder:validation:Optional
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// (String) The API endpoint containing the key that Access uses to verify that the response came from your API.
	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	// +kubebuilder:validation:Optional
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type RequireGithubInitParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type RequireGithubObservation struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type RequireGithubParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Github identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the organization.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The teams that should be matched.
	// The teams that should be matched.
	// +kubebuilder:validation:Optional
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type RequireGsuiteInitParameters struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireGsuiteObservation struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireGsuiteParameters struct {

	// (List of String) The email of the user.
	// The email of the Google Workspace group.
	// +kubebuilder:validation:Optional
	Email []*string `json:"email" tf:"email,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type RequireInitParameters struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	AuthContext []RequireAuthContextInitParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	Azure []RequireAzureInitParameters `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	ExternalEvaluation []RequireExternalEvaluationInitParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	Github []RequireGithubInitParameters `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	Gsuite []RequireGsuiteInitParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	Okta []RequireOktaInitParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	SAML []RequireSAMLInitParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type RequireObservation struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	AuthContext []RequireAuthContextObservation `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	Azure []RequireAzureObservation `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	ExternalEvaluation []RequireExternalEvaluationObservation `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	Github []RequireGithubObservation `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	Gsuite []RequireGsuiteObservation `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	Okta []RequireOktaObservation `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	SAML []RequireSAMLObservation `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type RequireOktaInitParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type RequireOktaObservation struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type RequireOktaParameters struct {

	// (String) The ID of the Azure identity provider.
	// The ID of your Okta identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// (String)
	// The name of the Okta Group.
	// +kubebuilder:validation:Optional
	Name []*string `json:"name,omitempty" tf:"name,omitempty"`
}

type RequireParameters struct {

	// (Boolean) Matches any valid Access service token.
	// Matches any valid Access service token.
	// +kubebuilder:validation:Optional
	AnyValidServiceToken *bool `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// (Block List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AuthContext []RequireAuthContextParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// 2 for possible types.
	// The type of authentication method. Refer to https://datatracker.ietf.org/doc/html/rfc8176#section-2 for possible types.
	// +kubebuilder:validation:Optional
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// (Block List) Matches an Azure group. Requires an Azure identity provider. (see below for nested schema)
	// Matches an Azure group. Requires an Azure identity provider.
	// +kubebuilder:validation:Optional
	Azure []RequireAzureParameters `json:"azure,omitempty" tf:"azure,omitempty"`

	// (Boolean) Matches any valid client certificate.
	// Matches any valid client certificate.
	// +kubebuilder:validation:Optional
	Certificate *bool `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) Matches a valid client certificate common name.
	// Matches a valid client certificate common name.
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (List of String) Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// Overflow field if you need to have multiple common_name rules in a single policy.  Use in place of the singular common_name field.
	// +kubebuilder:validation:Optional
	CommonNames []*string `json:"commonNames,omitempty" tf:"common_names,omitempty"`

	// (List of String) The ID of a device posture integration.
	// The ID of a device posture integration.
	// +kubebuilder:validation:Optional
	DevicePosture []*string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (List of String) The email of the user.
	// The email of the user.
	// +kubebuilder:validation:Optional
	Email []*string `json:"email,omitempty" tf:"email,omitempty"`

	// (List of String) The email domain to match.
	// The email domain to match.
	// +kubebuilder:validation:Optional
	EmailDomain []*string `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// (List of String) The ID of a previously created email list.
	// The ID of a previously created email list.
	// +kubebuilder:validation:Optional
	EmailList []*string `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// (Boolean) Matches everyone.
	// Matches everyone.
	// +kubebuilder:validation:Optional
	Everyone *bool `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// one/policies/access/external-evaluation/. (see below for nested schema)
	// Create Allow or Block policies which evaluate the user based on custom criteria. https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/.
	// +kubebuilder:validation:Optional
	ExternalEvaluation []RequireExternalEvaluationParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// (List of String) Matches a specific country.
	// Matches a specific country.
	// +kubebuilder:validation:Optional
	Geo []*string `json:"geo,omitempty" tf:"geo,omitempty"`

	// (Block List) Matches a Github organization. Requires a Github identity provider. (see below for nested schema)
	// Matches a Github organization. Requires a Github identity provider.
	// +kubebuilder:validation:Optional
	Github []RequireGithubParameters `json:"github,omitempty" tf:"github,omitempty"`

	// (List of String) The ID of a previously created Access group.
	// The ID of a previously created Access group.
	// +kubebuilder:validation:Optional
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// (Block List) Matches a group in Google Workspace. Requires a Google Workspace identity provider. (see below for nested schema)
	// Matches a group in Google Workspace. Requires a Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	Gsuite []RequireGsuiteParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// (List of String) An IPv4 or IPv6 CIDR block.
	// An IPv4 or IPv6 CIDR block.
	// +kubebuilder:validation:Optional
	IP []*string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (List of String) The ID of a previously created IP list.
	// The ID of a previously created IP list.
	// +kubebuilder:validation:Optional
	IPList []*string `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// (List of String) The ID of a configured identity provider.
	// The ID of a configured identity provider.
	// +kubebuilder:validation:Optional
	LoginMethod []*string `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// (Block List) Matches an Okta group. Requires an Okta identity provider. (see below for nested schema)
	// Matches an Okta group. Requires an Okta identity provider.
	// +kubebuilder:validation:Optional
	Okta []RequireOktaParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// (Block List) Matches a SAML group. Requires a SAML identity provider. (see below for nested schema)
	// Matches a SAML group. Requires a SAML identity provider.
	// +kubebuilder:validation:Optional
	SAML []RequireSAMLParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// (List of String) The ID of an Access service token.
	// The ID of an Access service token.
	// +kubebuilder:validation:Optional
	ServiceToken []*string `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type RequireSAMLInitParameters struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireSAMLObservation struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type RequireSAMLParameters struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	// +kubebuilder:validation:Optional
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	// +kubebuilder:validation:Optional
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type SAMLInitParameters struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type SAMLObservation struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type SAMLParameters struct {

	// (String) The name of the SAML attribute.
	// The name of the SAML attribute.
	// +kubebuilder:validation:Optional
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// (String) The SAML attribute value to look for.
	// The SAML attribute value to look for.
	// +kubebuilder:validation:Optional
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// (String) The ID of the Azure identity provider.
	// The ID of your SAML identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

// GroupSpec defines the desired state of Group
type GroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupInitParameters `json:"initProvider,omitempty"`
}

// GroupStatus defines the observed state of Group.
type GroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Group is the Schema for the Groups API. Provides a Cloudflare Access Group resource. Access Groups are used in conjunction with Access Policies to restrict access to a particular resource based on group membership.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type Group struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.include) || (has(self.initProvider) && has(self.initProvider.include))",message="spec.forProvider.include is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   GroupSpec   `json:"spec"`
	Status GroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupList contains a list of Groups
type GroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Group `json:"items"`
}

// Repository type metadata.
var (
	Group_Kind             = "Group"
	Group_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Group_Kind}.String()
	Group_KindAPIVersion   = Group_Kind + "." + CRDGroupVersion.String()
	Group_GroupVersionKind = CRDGroupVersion.WithKind(Group_Kind)
)

func init() {
	SchemeBuilder.Register(&Group{}, &GroupList{})
}
