apiVersion: access.cloudflare.m.holybitsllc.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: access/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: test_policy
  name: test-policy
  namespace: crossplane-system
spec:
  forProvider:
    accountId: f037e56e89293a057740de681ac9abbe
    decision: allow
    include:
    - email:
      - test@example.com
    name: staging policy
    require:
    - email:
      - test@example.com
